# STAGE 0
  FROM cgr.dev/chainguard/clang:1.20-dev as builder
  ENV APP_HOME=/app
  RUN useradd -m -s /bin/bash -d $APP_HOME myappuser
  WORKDIR $APP_HOME
  RUN apk --no-cache add clang clang-dev alpine-sdk dpkg \
      && apk --no-cache add --update cmake \
      && apk --no-cache add --update ccache
  COPY src/ $APP_HOME/src/ \
      && Makefile $APP_HOME/
  RUN --no-cache make -C $APP_HOME

# STAGE 1
  FROM cgr.dev/chainguard/static:1.20
  ENV APP_USER=myappuser
  ENV APP_HOME=/app
  RUN useradd -m -s /bin/bash -d $APP_HOME $APP_USER
  WORKDIR $APP_HOME
  COPY --from=builder $APP_HOME/myapp $APP_HOME/myapp
  USER $APP_USER
  ENTRYPOINT ["./myapp"]
