name: ci
on:
  push:
    branches:
      - "*"
      - main
  pull_request:

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  pull-requests: read

jobs:
  golangci:
    name: "run ci"
    strategy:
      matrix:
        os: ["windows-latest", "ubuntu-latest", "macOS-latest"]
        go: ["1.20", "1.21"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
          cache: false
      - name: Run tests
        run: go test ./... -coverprofile=coverage.out -coverpkg=./... -covermode=atomic
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
          args: -v --config=.ci.yml
      - name: Static check
        uses: dominikh/staticcheck-action@v1.3.0
        with:
          version: "23.1.6"
          install-go: false
          cache-key: ${matrix.go}