#
# Releaser workflow setup
# https://goreleaser.com/ci/actions/
#
name: release

# run only on tags
on:
  push:
    tags:
      - 'v*'  # Run pn Push tag 

permissions:
   contents: write # needed to write releases
   id-token: write # needed for keyless signing
   packages: write # needed for ghcr access

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # this is important, otherwise it won't checkout the full tree (i.e. no previous tags)
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21    # Go version
          cache: true
      - name: Run tests
        run: go test ./... -coverprofile=coverage.out -coverpkg=./... -covermode=atomic
        
      - uses: sigstore/cosign-installer@v3.4.0       # installs cosign
      - uses: anchore/sbom-action/download-syft@v0.14.3 # installs syft
      - uses: goreleaser/goreleaser-action@v5          # run goreleaser
        id: goreleaser
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: verify release
        run: |
          bash ./veify.sh


















      #     COMMIT=$(git rev-list --tags --max-count=1)
      #     TAG=$(git describe --tags ${COMMIT})
      #     wget https://github.com/intelops/genval/releases/download/${TAG}/checksums.txt
      #     cosign verify-blob \
      #       --certificate-identity "https://github.com/intelops/genval/.github/workflows/release.yaml@refs/tags/${TAG}" \
      #       --certificate-oidc-issuer "https://token.actions.githubusercontent.com" \
      #       --cert "https://github.com/intelops/genval/releases/download/${TAG}/checksums.txt.pem" \
      #       --signature "https://github.com/intelops/genval/releases/download/${TAG}/checksums.txt.sig" \
      #       ./checksums.txt
          

# NEW Release Verify command:

# curl -L -O https://github.com/santoshkal/genval-fork/releases/download/v0.1.3/genval-0.1.3.tar.gz \
  # -O https://github.com/santoshkal/genval-fork/releases/download/v0.1.3/genval-0.1.3.tar.gz.pem \
  # -O https://github.com/santoshkal/genval-fork/releases/download/v0.1.3/genval-0.1.3.tar.gz.sig

  # cosign verify-blob \
  # --signature ./genval-0.1.3.tar.gz.sig \
  # --cert ./genval-0.1.3.tar.gz.crt \
  # --certificate-oidc-issuer "https://token.actions.githubusercontent.com" \
  # --certificate-identity "https://github.com/intelops/genval/.github/workflows/release.yaml@refs/tags/v0.1.3" \
  # ./genval-0.1.3.tar.gz
 
          
        
      